/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package yahoo.micronaut

import com.google.common.io.Resources
import io.micronaut.http.HttpRequest
import io.micronaut.http.client.HttpClient
import io.micronaut.http.client.annotation.Client
import io.micronaut.test.extensions.junit5.annotation.MicronautTest
import jakarta.inject.Inject
import yahoo.micronaut.controller.getStockPriceFromResponse
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {

    @Test
    fun `parse a yahoo response to get a response that contains a current price`() {
        val responseHTML = Resources.getResource("response.txt").readText()
        val response = getStockPriceFromResponse(responseHTML, "WLD.PA")

        assertEquals(response?.regularMarketPrice?.raw, 278.37)
    }
}

@MicronautTest
class YahooControllerTest {
    @Inject
    @field:Client("/")
    lateinit var client: HttpClient

    @Test
    fun `request the api endpoint and expect to have a result, that is not null`() {
        val request: HttpRequest<Any> = HttpRequest.GET("/api/WLD.PA")
        val body = client.toBlocking().retrieve(request)
        assertNotNull(body)
        assert(body.length > 100)
    }

    @Test
    fun `request the health endpoint and get an status up as response`() {
        val request: HttpRequest<Any> = HttpRequest.GET("/health")
        val m = client.toBlocking().retrieve(request, Map::class.java)
        assertNotNull(m)
        assert(m.containsKey("status"))
        assertEquals(m.get("status"), "UP")
    }
}
