/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package yahoo.micronaut

import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlin.system.measureTimeMillis

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

val TICKER = arrayListOf("WLD.PA", "NADQ.F", "E127.DE", "QDVE.DE")

public fun main() {
    val time = measureTimeMillis {
        runBlocking {
            for (ticker in TICKER) {
                launch {
                    println("$ticker : ${loadStockPrice(ticker)?.regularMarketPrice?.raw}")
                }
            }
            println("started all routines")
        }
    }
    println("Completed in $time ms")
}
